project_id = "socrnutfpqtcjmetskta"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "https://socrnutfpqtcjmetskta.supabase.co"

[functions.unified-meta-review]
verify_jwt = false

[functions.daily-google-review]
verify_jwt = false

[functions.create-clickup-project]
verify_jwt = false

[functions.create-discord-channel]
verify_jwt = false

[functions.create-drive-folder]
verify_jwt = false

[functions.orchestrate-client-onboarding]
verify_jwt = false

[functions.refresh-meta-token]
verify_jwt = false

[functions.create-clickup-offboarding]
verify_jwt = false

[functions.orchestrate-client-offboarding]
verify_jwt = false

